/**
 * @packageDocumentation
 * @module api.functional.advice
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type { IConnection } from "@nestia/fetcher";
import { PlainFetcher } from "@nestia/fetcher";
import type { Resolved } from "typia";
import typia from "typia";

import type { IAdviceResult } from "../../structures/IAdviceResult";

/**
 * 유저의 약점 데이터 기반 개인화 학습 조언을 생성한다.
 *
 * UserQuestionStats에서 정답률이 낮은 태그를 분석하여
 * Gemini로 맞춤형 학습 조언을 생성한다.
 *
 * @tag Advice
 *
 * @controller AdviceController.getAdvice
 * @path GET /advice
 * @accessor api.functional.advice.getAdvice
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function getAdvice(
  connection: IConnection,
): Promise<getAdvice.Output> {
  return true === connection.simulate
    ? getAdvice.simulate(connection)
    : PlainFetcher.fetch(connection, {
        ...getAdvice.METADATA,
        template: getAdvice.METADATA.path,
        path: getAdvice.path(),
      });
}
export namespace getAdvice {
  export type Output = IAdviceResult;

  export const METADATA = {
    method: "GET",
    path: "/advice",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = () => "/advice";
  export const random = (): Resolved<IAdviceResult> =>
    typia.random<IAdviceResult>();
  export const simulate = (_connection: IConnection): Output => {
    return random();
  };
}
