/**
 * @packageDocumentation
 * @module api.functional.domains.tags
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type { IConnection } from "@nestia/fetcher";
import { NestiaSimulator, PlainFetcher } from "@nestia/fetcher";
import type { Resolved, tags } from "typia";
import typia from "typia";

/**
 * 특정 도메인의 태그 목록 조회.
 *
 * @tag Domain
 *
 * @controller DomainController.getTagsByDomain
 * @path GET /domains/:domainId/tags
 * @accessor api.functional.domains.tags.getTagsByDomain
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function getTagsByDomain(
  connection: IConnection,
  domainId: string,
): Promise<getTagsByDomain.Output> {
  return true === connection.simulate
    ? getTagsByDomain.simulate(connection, domainId)
    : PlainFetcher.fetch(connection, {
        ...getTagsByDomain.METADATA,
        template: getTagsByDomain.METADATA.path,
        path: getTagsByDomain.path(domainId),
      });
}
export namespace getTagsByDomain {
  export type Output = {
    id: string;
    name: string;
    created_at: string & tags.Format<"date-time">;
    domain_id: string;
    created_by: string;
  }[];

  export const METADATA = {
    method: "GET",
    path: "/domains/:domainId/tags",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = (domainId: string) =>
    `/domains/${encodeURIComponent(domainId?.toString() ?? "null")}/tags`;
  export const random = (): Resolved<
    {
      id: string;
      name: string;
      created_at: string & tags.Format<"date-time">;
      domain_id: string;
      created_by: string;
    }[]
  > =>
    typia.random<
      {
        id: string;
        name: string;
        created_at: string & tags.Format<"date-time">;
        domain_id: string;
        created_by: string;
      }[]
    >();
  export const simulate = (
    connection: IConnection,
    domainId: string,
  ): Output => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: path(domainId),
      contentType: "application/json",
    });
    assert.param("domainId")(() => typia.assert(domainId));
    return random();
  };
}
