/**
 * @packageDocumentation
 * @module api.functional.goals.deactivate
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type { IConnection } from "@nestia/fetcher";
import { NestiaSimulator, PlainFetcher } from "@nestia/fetcher";
import type { Resolved } from "typia";
import typia from "typia";

/**
 * 목표 비활성화.
 *
 * @tag Goal
 *
 * @controller GoalController.deactivateGoal
 * @path PATCH /goals/:goalId/deactivate
 * @accessor api.functional.goals.deactivate.deactivateGoal
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function deactivateGoal(
  connection: IConnection,
  goalId: string,
): Promise<deactivateGoal.Output> {
  return true === connection.simulate
    ? deactivateGoal.simulate(connection, goalId)
    : PlainFetcher.fetch(connection, {
        ...deactivateGoal.METADATA,
        template: deactivateGoal.METADATA.path,
        path: deactivateGoal.path(goalId),
      });
}
export namespace deactivateGoal {
  export type Output = {
    success: boolean;
  };

  export const METADATA = {
    method: "PATCH",
    path: "/goals/:goalId/deactivate",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = (goalId: string) =>
    `/goals/${encodeURIComponent(goalId?.toString() ?? "null")}/deactivate`;
  export const random = (): Resolved<{
    success: boolean;
  }> =>
    typia.random<{
      success: boolean;
    }>();
  export const simulate = (connection: IConnection, goalId: string): Output => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: path(goalId),
      contentType: "application/json",
    });
    assert.param("goalId")(() => typia.assert(goalId));
    return random();
  };
}
