/**
 * @packageDocumentation
 * @module api.functional.domains
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type { IConnection } from "@nestia/fetcher";
import { PlainFetcher } from "@nestia/fetcher";
import type { Resolved } from "typia";
import typia from "typia";

import type { IDomainItem } from "../../structures/IDomainItem";

export * as me from "./me/index";
export * as roadmap from "./roadmap/index";
export * as tags from "./tags/index";
export * as search from "./search/index";

/**
 * 전체 도메인 목록 조회.
 *
 * @tag Domain
 *
 * @controller DomainController.getAllDomains
 * @path GET /domains
 * @accessor api.functional.domains.getAllDomains
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function getAllDomains(
  connection: IConnection,
): Promise<getAllDomains.Output> {
  return true === connection.simulate
    ? getAllDomains.simulate(connection)
    : PlainFetcher.fetch(connection, {
        ...getAllDomains.METADATA,
        template: getAllDomains.METADATA.path,
        path: getAllDomains.path(),
      });
}
export namespace getAllDomains {
  export type Output = IDomainItem[];

  export const METADATA = {
    method: "GET",
    path: "/domains",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = () => "/domains";
  export const random = (): Resolved<IDomainItem[]> =>
    typia.random<IDomainItem[]>();
  export const simulate = (_connection: IConnection): Output => {
    return random();
  };
}
