/**
 * @packageDocumentation
 * @module api.functional
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type { IConnection } from "@nestia/fetcher";
import { PlainFetcher } from "@nestia/fetcher";
import type { Resolved } from "typia";
import typia from "typia";

export * as health from "./health/index";
export * as stats from "./stats/index";
export * as sessions from "./sessions/index";
export * as roadmaps from "./roadmaps/index";
export * as questions from "./questions/index";
export * as payments from "./payments/index";
export * as onboarding from "./onboarding/index";
export * as goals from "./goals/index";
export * as domains from "./domains/index";
export * as auth from "./auth/index";
export * as answers from "./answers/index";
export * as advice from "./advice/index";

/**
 * @controller AppController.getHello
 * @path GET /
 * @accessor api.functional.getHello
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function getHello(
  connection: IConnection,
): Promise<getHello.Output> {
  return true === connection.simulate
    ? getHello.simulate(connection)
    : PlainFetcher.fetch(connection, {
        ...getHello.METADATA,
        template: getHello.METADATA.path,
        path: getHello.path(),
      });
}
export namespace getHello {
  export type Output = string;

  export const METADATA = {
    method: "GET",
    path: "/",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = () => "/";
  export const random = (): Resolved<string> => typia.random<string>();
  export const simulate = (_connection: IConnection): Output => {
    return random();
  };
}
