/**
 * @packageDocumentation
 * @module api.functional.health
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type { IConnection } from "@nestia/fetcher";
import { PlainFetcher } from "@nestia/fetcher";
import type { Resolved } from "typia";
import typia from "typia";

/**
 * @controller AppController.getHealth
 * @path GET /health
 * @accessor api.functional.health.getHealth
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function getHealth(
  connection: IConnection,
): Promise<getHealth.Output> {
  return true === connection.simulate
    ? getHealth.simulate(connection)
    : PlainFetcher.fetch(connection, {
        ...getHealth.METADATA,
        template: getHealth.METADATA.path,
        path: getHealth.path(),
      });
}
export namespace getHealth {
  export type Output = {
    status: string;
  };

  export const METADATA = {
    method: "GET",
    path: "/health",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = () => "/health";
  export const random = (): Resolved<{
    status: string;
  }> =>
    typia.random<{
      status: string;
    }>();
  export const simulate = (_connection: IConnection): Output => {
    return random();
  };
}
