/**
 * @packageDocumentation
 * @module api.functional.onboarding
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type { IConnection } from "@nestia/fetcher";
import { NestiaSimulator, PlainFetcher } from "@nestia/fetcher";
import type { Resolved } from "typia";
import typia from "typia";

import type { IOnboardingChatBody } from "../../structures/IOnboardingChatBody";
import type { IOnboardingChatResult } from "../../structures/IOnboardingChatResult";

/**
 * 온보딩 대화 처리 (최대 3턴).
 * 유저 입력 → 도메인/태그 추천 → 목표 확정.
 *
 * @tag Onboarding
 *
 * @controller OnboardingController.chat
 * @path POST /onboarding/chat
 * @accessor api.functional.onboarding.chat
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function chat(
  connection: IConnection,
  body: chat.Body,
): Promise<chat.Output> {
  return true === connection.simulate
    ? chat.simulate(connection, body)
    : PlainFetcher.fetch(
        {
          ...connection,
          headers: {
            ...connection.headers,
            "Content-Type": "application/json",
          },
        },
        {
          ...chat.METADATA,
          template: chat.METADATA.path,
          path: chat.path(),
        },
        body,
      );
}
export namespace chat {
  export type Body = IOnboardingChatBody;
  export type Output = IOnboardingChatResult;

  export const METADATA = {
    method: "POST",
    path: "/onboarding/chat",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 201,
  } as const;

  export const path = () => "/onboarding/chat";
  export const random = (): Resolved<IOnboardingChatResult> =>
    typia.random<IOnboardingChatResult>();
  export const simulate = (connection: IConnection, body: Body): Output => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: path(),
      contentType: "application/json",
    });
    assert.body(() => typia.assert(body));
    return random();
  };
}
