/**
 * @packageDocumentation
 * @module api.functional.domains.search
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type { IConnection } from "@nestia/fetcher";
import { NestiaSimulator, PlainFetcher } from "@nestia/fetcher";
import type { Resolved } from "typia";
import typia from "typia";

import type { IDomainSearchBody } from "../../../structures/IDomainSearchBody";
import type { IDomainSearchResult } from "../../../structures/IDomainSearchResult";

/**
 * 유저 자연어 입력으로 도메인 검색.
 * Gemini로 태그 추출 + 임베딩 유사도 검색.
 *
 * @tag Domain
 *
 * @controller DomainController.searchDomains
 * @path POST /domains/search
 * @accessor api.functional.domains.search.searchDomains
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function searchDomains(
  connection: IConnection,
  body: searchDomains.Body,
): Promise<searchDomains.Output> {
  return true === connection.simulate
    ? searchDomains.simulate(connection, body)
    : PlainFetcher.fetch(
        {
          ...connection,
          headers: {
            ...connection.headers,
            "Content-Type": "application/json",
          },
        },
        {
          ...searchDomains.METADATA,
          template: searchDomains.METADATA.path,
          path: searchDomains.path(),
        },
        body,
      );
}
export namespace searchDomains {
  export type Body = IDomainSearchBody;
  export type Output = IDomainSearchResult;

  export const METADATA = {
    method: "POST",
    path: "/domains/search",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 201,
  } as const;

  export const path = () => "/domains/search";
  export const random = (): Resolved<IDomainSearchResult> =>
    typia.random<IDomainSearchResult>();
  export const simulate = (connection: IConnection, body: Body): Output => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: path(),
      contentType: "application/json",
    });
    assert.body(() => typia.assert(body));
    return random();
  };
}
