/**
 * @packageDocumentation
 * @module api.functional.payments.nonce
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type { IConnection } from "@nestia/fetcher";
import { NestiaSimulator, PlainFetcher } from "@nestia/fetcher";
import type { Resolved } from "typia";
import typia from "typia";

import type { IGenerateNonceBody } from "../../../structures/IGenerateNonceBody";
import type { IGenerateNonceResult } from "../../../structures/IGenerateNonceResult";

/**
 * 신규 결제 reference 생성.
 *
 * QZ-TASK-010에서 App Store/웹 결제 재설계를 마칠 때까지 비활성화한다.
 *
 * @tag Payment
 *
 * @controller PaymentController.generateNonce
 * @path POST /payments/nonce
 * @accessor api.functional.payments.nonce.generateNonce
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function generateNonce(
  connection: IConnection,
  body: generateNonce.Body,
): Promise<generateNonce.Output> {
  return true === connection.simulate
    ? generateNonce.simulate(connection, body)
    : PlainFetcher.fetch(
        {
          ...connection,
          headers: {
            ...connection.headers,
            "Content-Type": "application/json",
          },
        },
        {
          ...generateNonce.METADATA,
          template: generateNonce.METADATA.path,
          path: generateNonce.path(),
        },
        body,
      );
}
export namespace generateNonce {
  export type Body = IGenerateNonceBody;
  export type Output = IGenerateNonceResult;

  export const METADATA = {
    method: "POST",
    path: "/payments/nonce",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 201,
  } as const;

  export const path = () => "/payments/nonce";
  export const random = (): Resolved<IGenerateNonceResult> =>
    typia.random<IGenerateNonceResult>();
  export const simulate = (connection: IConnection, body: Body): Output => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: path(),
      contentType: "application/json",
    });
    assert.body(() => typia.assert(body));
    return random();
  };
}
