/**
 * @packageDocumentation
 * @module api.functional.payments.pending
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type { IConnection } from "@nestia/fetcher";
import { PlainFetcher } from "@nestia/fetcher";
import type { Resolved } from "typia";
import typia from "typia";

import type { IPaymentItem } from "../../../structures/IPaymentItem";

/**
 * 미완료(pending) 결제 조회 — 프론트 재진입 시 자동 confirm용.
 *
 * @tag Payment
 *
 * @controller PaymentController.getPending
 * @path GET /payments/pending
 * @accessor api.functional.payments.pending.getPending
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function getPending(
  connection: IConnection,
): Promise<getPending.Output> {
  return true === connection.simulate
    ? getPending.simulate(connection)
    : PlainFetcher.fetch(connection, {
        ...getPending.METADATA,
        template: getPending.METADATA.path,
        path: getPending.path(),
      });
}
export namespace getPending {
  export type Output = null | IPaymentItem;

  export const METADATA = {
    method: "GET",
    path: "/payments/pending",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = () => "/payments/pending";
  export const random = (): Resolved<null | IPaymentItem> =>
    typia.random<null | IPaymentItem>();
  export const simulate = (_connection: IConnection): Output => {
    return random();
  };
}
