/**
 * @packageDocumentation
 * @module api.functional.sessions
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type { IConnection } from "@nestia/fetcher";
import { NestiaSimulator, PlainFetcher } from "@nestia/fetcher";
import type { Resolved } from "typia";
import typia from "typia";

import type { ICreateSession } from "../../structures/ICreateSession";
import type { ISession } from "../../structures/ISession";
import type { ISessionCompleteResult } from "../../structures/ISessionCompleteResult";

/**
 * 학습 세션을 구성한다.
 *
 * 체크포인트의 tag + difficulty를 기반으로 문제 은행에서 ~15문제를 선택한다.
 * HLR 알고리즘으로 p(recall) < 0.5인 복습 대상을 ~40% 비율로 포함하고,
 * 나머지 ~60%는 새 문제로 채운다.
 *
 * 응답에는 정답(answer)이 포함되지 않는다.
 * 정답 확인은 POST /answers로 답안을 제출해야 한다.
 *
 * @param body checkpoint_id
 * @tag Sessions
 *
 * @controller SessionsController.create
 * @path POST /sessions
 * @accessor api.functional.sessions.create
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function create(
  connection: IConnection,
  body: create.Body,
): Promise<create.Output> {
  return true === connection.simulate
    ? create.simulate(connection, body)
    : PlainFetcher.fetch(
        {
          ...connection,
          headers: {
            ...connection.headers,
            "Content-Type": "application/json",
          },
        },
        {
          ...create.METADATA,
          template: create.METADATA.path,
          path: create.path(),
        },
        body,
      );
}
export namespace create {
  export type Body = ICreateSession;
  export type Output = ISession;

  export const METADATA = {
    method: "POST",
    path: "/sessions",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 201,
  } as const;

  export const path = () => "/sessions";
  export const random = (): Resolved<ISession> => typia.random<ISession>();
  export const simulate = (connection: IConnection, body: Body): Output => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: path(),
      contentType: "application/json",
    });
    assert.body(() => typia.assert(body));
    return random();
  };
}

/**
 * 세션을 완료하고 체크포인트를 평가한다.
 *
 * 세션에 연결된 답안을 기반으로 점수를 계산하고,
 * 체크포인트의 best_score, attempts, status를 갱신한다.
 *
 * @param sessionId 세션 ID
 * @tag Sessions
 *
 * @controller SessionsController.complete
 * @path POST /sessions/:sessionId/complete
 * @accessor api.functional.sessions.complete
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function complete(
  connection: IConnection,
  sessionId: string,
): Promise<complete.Output> {
  return true === connection.simulate
    ? complete.simulate(connection, sessionId)
    : PlainFetcher.fetch(connection, {
        ...complete.METADATA,
        template: complete.METADATA.path,
        path: complete.path(sessionId),
      });
}
export namespace complete {
  export type Output = ISessionCompleteResult;

  export const METADATA = {
    method: "POST",
    path: "/sessions/:sessionId/complete",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 201,
  } as const;

  export const path = (sessionId: string) =>
    `/sessions/${encodeURIComponent(sessionId?.toString() ?? "null")}/complete`;
  export const random = (): Resolved<ISessionCompleteResult> =>
    typia.random<ISessionCompleteResult>();
  export const simulate = (
    connection: IConnection,
    sessionId: string,
  ): Output => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: path(sessionId),
      contentType: "application/json",
    });
    assert.param("sessionId")(() => typia.assert(sessionId));
    return random();
  };
}
