/**
 * @packageDocumentation
 * @module api.functional.domains.roadmap
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type { IConnection } from "@nestia/fetcher";
import { NestiaSimulator, PlainFetcher } from "@nestia/fetcher";
import type { Resolved } from "typia";
import typia from "typia";

import type { IDomainRoadmap } from "../../../structures/IDomainRoadmap";

/**
 * 특정 도메인의 유저 로드맵 조회.
 *
 * @tag Domain
 *
 * @controller DomainController.getDomainRoadmap
 * @path GET /domains/:domainId/roadmap
 * @accessor api.functional.domains.roadmap.getDomainRoadmap
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function getDomainRoadmap(
  connection: IConnection,
  domainId: string,
): Promise<getDomainRoadmap.Output> {
  return true === connection.simulate
    ? getDomainRoadmap.simulate(connection, domainId)
    : PlainFetcher.fetch(connection, {
        ...getDomainRoadmap.METADATA,
        template: getDomainRoadmap.METADATA.path,
        path: getDomainRoadmap.path(domainId),
      });
}
export namespace getDomainRoadmap {
  export type Output = null | IDomainRoadmap.o1;

  export const METADATA = {
    method: "GET",
    path: "/domains/:domainId/roadmap",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = (domainId: string) =>
    `/domains/${encodeURIComponent(domainId?.toString() ?? "null")}/roadmap`;
  export const random = (): Resolved<null | IDomainRoadmap.o1> =>
    typia.random<null | IDomainRoadmap.o1>();
  export const simulate = (
    connection: IConnection,
    domainId: string,
  ): Output => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: path(domainId),
      contentType: "application/json",
    });
    assert.param("domainId")(() => typia.assert(domainId));
    return random();
  };
}
