/**
 * @packageDocumentation
 * @module api.functional.auth.dev_login
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type { IConnection } from "@nestia/fetcher";
import { NestiaSimulator, PlainFetcher } from "@nestia/fetcher";
import type { Resolved } from "typia";
import typia from "typia";

import type { IAuthResponse } from "../../../structures/IAuthResponse";
import type { IDevLogin } from "../../../structures/IDevLogin";

/**
 * 개발 환경 전용 로그인.
 *
 * 프로덕션에서는 비활성화됨 (ENABLE_DEV_LOGIN=true로 강제 활성화 가능).
 * World ID 검증 없이 즉시 JWT를 발급한다.
 *
 * @param body 테스트용 world_id (선택)
 * @tag Auth
 *
 * @controller AuthController.devLogin
 * @path POST /auth/dev-login
 * @accessor api.functional.auth.dev_login.devLogin
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function devLogin(
  connection: IConnection,
  body: devLogin.Body,
): Promise<devLogin.Output> {
  return true === connection.simulate
    ? devLogin.simulate(connection, body)
    : PlainFetcher.fetch(
        {
          ...connection,
          headers: {
            ...connection.headers,
            "Content-Type": "application/json",
          },
        },
        {
          ...devLogin.METADATA,
          template: devLogin.METADATA.path,
          path: devLogin.path(),
        },
        body,
      );
}
export namespace devLogin {
  export type Body = IDevLogin;
  export type Output = IAuthResponse;

  export const METADATA = {
    method: "POST",
    path: "/auth/dev-login",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 201,
  } as const;

  export const path = () => "/auth/dev-login";
  export const random = (): Resolved<IAuthResponse> =>
    typia.random<IAuthResponse>();
  export const simulate = (connection: IConnection, body: Body): Output => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: path(),
      contentType: "application/json",
    });
    assert.body(() => typia.assert(body));
    return random();
  };
}
