/**
 * @packageDocumentation
 * @module api.functional.answers
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type { IConnection } from "@nestia/fetcher";
import { NestiaSimulator, PlainFetcher } from "@nestia/fetcher";
import type { Resolved } from "typia";
import typia from "typia";

import type { IAnswerResult } from "../../structures/IAnswerResult";
import type { ISubmitAnswer } from "../../structures/ISubmitAnswer";

/**
 * 답안을 제출하고 채점 결과를 받는다.
 *
 * 문제의 정답과 비교하여 채점 후 결과를 반환한다.
 * 동시에 UserAnswer 레코드를 저장하고,
 * HLR 반감기(UserQuestionStats)를 갱신한다.
 *
 * HLR 규칙:
 * - 정답 → half_life × 2 (복습 간격 증가)
 * - 오답 → half_life × 0.5 (복습 간격 감소)
 *
 * @param body question_id + user_answer + optional session_id
 * @tag Answers
 *
 * @controller AnswersController.submit
 * @path POST /answers
 * @accessor api.functional.answers.submit
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function submit(
  connection: IConnection,
  body: submit.Body,
): Promise<submit.Output> {
  return true === connection.simulate
    ? submit.simulate(connection, body)
    : PlainFetcher.fetch(
        {
          ...connection,
          headers: {
            ...connection.headers,
            "Content-Type": "application/json",
          },
        },
        {
          ...submit.METADATA,
          template: submit.METADATA.path,
          path: submit.path(),
        },
        body,
      );
}
export namespace submit {
  export type Body = ISubmitAnswer;
  export type Output = IAnswerResult;

  export const METADATA = {
    method: "POST",
    path: "/answers",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 201,
  } as const;

  export const path = () => "/answers";
  export const random = (): Resolved<IAnswerResult> =>
    typia.random<IAnswerResult>();
  export const simulate = (connection: IConnection, body: Body): Output => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: path(),
      contentType: "application/json",
    });
    assert.body(() => typia.assert(body));
    return random();
  };
}
