/**
 * @packageDocumentation
 * @module api.functional.domains.me
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type { IConnection } from "@nestia/fetcher";
import { PlainFetcher } from "@nestia/fetcher";
import type { Resolved } from "typia";
import typia from "typia";

import type { IDomainProgress } from "../../../structures/IDomainProgress";

/**
 * 현재 유저의 도메인 목록 + 진행률 조회.
 *
 * @tag Domain
 *
 * @controller DomainController.getUserDomains
 * @path GET /domains/me
 * @accessor api.functional.domains.me.getUserDomains
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function getUserDomains(
  connection: IConnection,
): Promise<getUserDomains.Output> {
  return true === connection.simulate
    ? getUserDomains.simulate(connection)
    : PlainFetcher.fetch(connection, {
        ...getUserDomains.METADATA,
        template: getUserDomains.METADATA.path,
        path: getUserDomains.path(),
      });
}
export namespace getUserDomains {
  export type Output = IDomainProgress[];

  export const METADATA = {
    method: "GET",
    path: "/domains/me",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = () => "/domains/me";
  export const random = (): Resolved<IDomainProgress[]> =>
    typia.random<IDomainProgress[]>();
  export const simulate = (_connection: IConnection): Output => {
    return random();
  };
}
