/**
 * @packageDocumentation
 * @module api.functional.roadmaps
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type { IConnection } from "@nestia/fetcher";
import { NestiaSimulator, PlainFetcher } from "@nestia/fetcher";
import type { Resolved } from "typia";
import typia from "typia";

import type { IDomainRoadmap } from "../../structures/IDomainRoadmap";

export * as match from "./match/index";

/**
 * Goal ID로 로드맵 조회 (체크포인트 포함).
 * 본인의 goal에 대한 로드맵만 조회 가능.
 *
 * @tag Roadmap
 *
 * @controller RoadmapController.getByGoalId
 * @path GET /roadmaps/:goalId
 * @accessor api.functional.roadmaps.getByGoalId
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function getByGoalId(
  connection: IConnection,
  goalId: string,
): Promise<getByGoalId.Output> {
  return true === connection.simulate
    ? getByGoalId.simulate(connection, goalId)
    : PlainFetcher.fetch(connection, {
        ...getByGoalId.METADATA,
        template: getByGoalId.METADATA.path,
        path: getByGoalId.path(goalId),
      });
}
export namespace getByGoalId {
  export type Output = null | IDomainRoadmap;

  export const METADATA = {
    method: "GET",
    path: "/roadmaps/:goalId",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = (goalId: string) =>
    `/roadmaps/${encodeURIComponent(goalId?.toString() ?? "null")}`;
  export const random = (): Resolved<null | IDomainRoadmap> =>
    typia.random<null | IDomainRoadmap>();
  export const simulate = (connection: IConnection, goalId: string): Output => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: path(goalId),
      contentType: "application/json",
    });
    assert.param("goalId")(() => typia.assert(goalId));
    return random();
  };
}
