/**
 * @packageDocumentation
 * @module api.functional.questions
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type { IConnection } from "@nestia/fetcher";
import { NestiaSimulator, PlainFetcher } from "@nestia/fetcher";
import type { Resolved } from "typia";
import typia from "typia";

import type { IGenerateQuestions } from "../../structures/IGenerateQuestions";
import type { IGenerateResult } from "../../structures/IGenerateResult";

/**
 * 프리미엄 유저 전용 — AI 문제를 생성한다.
 *
 * 태그, 난이도, 개수를 지정하면 해당 조건에 맞는 문제를 생성하여
 * question bank에 저장한다. 생성된 문제는 모든 유저가 사용할 수 있다.
 *
 * 현재는 플레이스홀더 문제를 반환하며, 추후 Gemini API 연동 예정.
 *
 * @param body 태그 + 난이도 + 생성 개수
 * @tag Questions
 *
 * @controller QuestionsController.generate
 * @path POST /questions/generate
 * @accessor api.functional.questions.generate
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function generate(
  connection: IConnection,
  body: generate.Body,
): Promise<generate.Output> {
  return true === connection.simulate
    ? generate.simulate(connection, body)
    : PlainFetcher.fetch(
        {
          ...connection,
          headers: {
            ...connection.headers,
            "Content-Type": "application/json",
          },
        },
        {
          ...generate.METADATA,
          template: generate.METADATA.path,
          path: generate.path(),
        },
        body,
      );
}
export namespace generate {
  export type Body = IGenerateQuestions;
  export type Output = IGenerateResult;

  export const METADATA = {
    method: "POST",
    path: "/questions/generate",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 201,
  } as const;

  export const path = () => "/questions/generate";
  export const random = (): Resolved<IGenerateResult> =>
    typia.random<IGenerateResult>();
  export const simulate = (connection: IConnection, body: Body): Output => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: path(),
      contentType: "application/json",
    });
    assert.body(() => typia.assert(body));
    return random();
  };
}
