/**
 * @packageDocumentation
 * @module api.functional.goals
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type { IConnection } from "@nestia/fetcher";
import { NestiaSimulator, PlainFetcher } from "@nestia/fetcher";
import type { Resolved } from "typia";
import typia from "typia";

import type { ICreateGoalBody } from "../../structures/ICreateGoalBody";
import type { ICreateGoalResult } from "../../structures/ICreateGoalResult";
import type { IGoalItem } from "../../structures/IGoalItem";

export * as deactivate from "./deactivate/index";

/**
 * 새 학습 목표 생성. 도메인이 없으면 자동 생성.
 * embedding 제공 시 유사 템플릿 로드맵 자동 매칭.
 *
 * @tag Goal
 *
 * @controller GoalController.createGoal
 * @path POST /goals
 * @accessor api.functional.goals.createGoal
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function createGoal(
  connection: IConnection,
  body: createGoal.Body,
): Promise<createGoal.Output> {
  return true === connection.simulate
    ? createGoal.simulate(connection, body)
    : PlainFetcher.fetch(
        {
          ...connection,
          headers: {
            ...connection.headers,
            "Content-Type": "application/json",
          },
        },
        {
          ...createGoal.METADATA,
          template: createGoal.METADATA.path,
          path: createGoal.path(),
        },
        body,
      );
}
export namespace createGoal {
  export type Body = ICreateGoalBody;
  export type Output = ICreateGoalResult;

  export const METADATA = {
    method: "POST",
    path: "/goals",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 201,
  } as const;

  export const path = () => "/goals";
  export const random = (): Resolved<ICreateGoalResult> =>
    typia.random<ICreateGoalResult>();
  export const simulate = (connection: IConnection, body: Body): Output => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: path(),
      contentType: "application/json",
    });
    assert.body(() => typia.assert(body));
    return random();
  };
}

/**
 * 현재 유저의 활성 목표 목록 조회.
 *
 * @tag Goal
 *
 * @controller GoalController.getUserGoals
 * @path GET /goals
 * @accessor api.functional.goals.getUserGoals
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function getUserGoals(
  connection: IConnection,
): Promise<getUserGoals.Output> {
  return true === connection.simulate
    ? getUserGoals.simulate(connection)
    : PlainFetcher.fetch(connection, {
        ...getUserGoals.METADATA,
        template: getUserGoals.METADATA.path,
        path: getUserGoals.path(),
      });
}
export namespace getUserGoals {
  export type Output = IGoalItem[];

  export const METADATA = {
    method: "GET",
    path: "/goals",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = () => "/goals";
  export const random = (): Resolved<IGoalItem[]> =>
    typia.random<IGoalItem[]>();
  export const simulate = (_connection: IConnection): Output => {
    return random();
  };
}
