/**
 * @packageDocumentation
 * @module api.functional.auth.wallet
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type { IConnection } from "@nestia/fetcher";
import { NestiaSimulator, PlainFetcher } from "@nestia/fetcher";
import type { Resolved } from "typia";
import typia from "typia";

import type { IAuthResponse } from "../../../structures/IAuthResponse";
import type { IWalletAuth } from "../../../structures/IWalletAuth";

/**
 * MiniKit walletAuth() 결과(SIWE 서명)를 검증하고 JWT를 발급한다.
 *
 * 인증 플로우:
 * 1. 프론트엔드 → GET /auth/nonce → nonce 획득
 * 2. 프론트엔드 → MiniKit.walletAuth({ nonce }) → SIWE 서명 획득
 * 3. 프론트엔드 → POST /auth/wallet { message, signature, address, nonce }
 * 4. 백엔드 → SIWE 검증 → 유저 upsert → JWT 발급 → 쿠키 세팅
 *
 * Mini App (World App webview) 전용. 네이티브 앱은 IDKit을 사용한다.
 *
 * @param body SIWE 서명 페이로드
 * @tag Auth
 *
 * @controller AuthController.walletAuth
 * @path POST /auth/wallet
 * @accessor api.functional.auth.wallet.walletAuth
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function walletAuth(
  connection: IConnection,
  body: walletAuth.Body,
): Promise<walletAuth.Output> {
  return true === connection.simulate
    ? walletAuth.simulate(connection, body)
    : PlainFetcher.fetch(
        {
          ...connection,
          headers: {
            ...connection.headers,
            "Content-Type": "application/json",
          },
        },
        {
          ...walletAuth.METADATA,
          template: walletAuth.METADATA.path,
          path: walletAuth.path(),
        },
        body,
      );
}
export namespace walletAuth {
  export type Body = IWalletAuth;
  export type Output = IAuthResponse;

  export const METADATA = {
    method: "POST",
    path: "/auth/wallet",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 201,
  } as const;

  export const path = () => "/auth/wallet";
  export const random = (): Resolved<IAuthResponse> =>
    typia.random<IAuthResponse>();
  export const simulate = (connection: IConnection, body: Body): Output => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: path(),
      contentType: "application/json",
    });
    assert.body(() => typia.assert(body));
    return random();
  };
}
