/**
 * @packageDocumentation
 * @module api.functional.stats
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type { IConnection } from "@nestia/fetcher";
import { PlainFetcher } from "@nestia/fetcher";
import type { Resolved } from "typia";
import typia from "typia";

import type { IStats } from "../../structures/IStats";

/**
 * 유저의 종합 학습 통계를 조회한다.
 *
 * 태그별 정답률, 총 답변 수, 로드맵 진행률을 반환한다.
 * 로드맵 진행률은 유저의 모든 로드맵에 대한 종합 진행률이다.
 *
 * @tag Stats
 *
 * @controller StatsController.getStats
 * @path GET /stats
 * @accessor api.functional.stats.getStats
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function getStats(
  connection: IConnection,
): Promise<getStats.Output> {
  return true === connection.simulate
    ? getStats.simulate(connection)
    : PlainFetcher.fetch(connection, {
        ...getStats.METADATA,
        template: getStats.METADATA.path,
        path: getStats.path(),
      });
}
export namespace getStats {
  export type Output = IStats;

  export const METADATA = {
    method: "GET",
    path: "/stats",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = () => "/stats";
  export const random = (): Resolved<IStats> => typia.random<IStats>();
  export const simulate = (_connection: IConnection): Output => {
    return random();
  };
}
