/**
 * @packageDocumentation
 * @module api.functional.payments.history
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type { IConnection } from "@nestia/fetcher";
import { PlainFetcher } from "@nestia/fetcher";
import type { Resolved } from "typia";
import typia from "typia";

import type { IPaymentItem } from "../../../structures/IPaymentItem";

/**
 * 결제 이력 조회.
 *
 * @tag Payment
 *
 * @controller PaymentController.getHistory
 * @path GET /payments/history
 * @accessor api.functional.payments.history.getHistory
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function getHistory(
  connection: IConnection,
): Promise<getHistory.Output> {
  return true === connection.simulate
    ? getHistory.simulate(connection)
    : PlainFetcher.fetch(connection, {
        ...getHistory.METADATA,
        template: getHistory.METADATA.path,
        path: getHistory.path(),
      });
}
export namespace getHistory {
  export type Output = IPaymentItem[];

  export const METADATA = {
    method: "GET",
    path: "/payments/history",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = () => "/payments/history";
  export const random = (): Resolved<IPaymentItem[]> =>
    typia.random<IPaymentItem[]>();
  export const simulate = (_connection: IConnection): Output => {
    return random();
  };
}
