/**
 * @packageDocumentation
 * @module api.functional.auth.social
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type { IConnection } from "@nestia/fetcher";
import { NestiaSimulator, PlainFetcher } from "@nestia/fetcher";
import type { Resolved } from "typia";
import typia from "typia";

import type { IAuthResponse } from "../../../structures/IAuthResponse";
import type { ISocialLogin } from "../../../structures/ISocialLogin";

/**
 * Google, Apple, Kakao 로그인 결과를 검증하고 JWT를 발급한다.
 *
 * `provider`별 token은 서버에서 검증하며, 유저는 `UserIdentity(provider, provider_user_id)`
 * 기준으로 조회하거나 생성한다. 서로 다른 provider의 동일 email은 자동 병합하지 않는다.
 *
 * @tag Auth
 *
 * @controller AuthController.socialLogin
 * @path POST /auth/social
 * @accessor api.functional.auth.social.socialLogin
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function socialLogin(
  connection: IConnection,
  body: socialLogin.Body,
): Promise<socialLogin.Output> {
  return true === connection.simulate
    ? socialLogin.simulate(connection, body)
    : PlainFetcher.fetch(
        {
          ...connection,
          headers: {
            ...connection.headers,
            "Content-Type": "application/json",
          },
        },
        {
          ...socialLogin.METADATA,
          template: socialLogin.METADATA.path,
          path: socialLogin.path(),
        },
        body,
      );
}
export namespace socialLogin {
  export type Body = ISocialLogin;
  export type Output = IAuthResponse;

  export const METADATA = {
    method: "POST",
    path: "/auth/social",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 201,
  } as const;

  export const path = () => "/auth/social";
  export const random = (): Resolved<IAuthResponse> =>
    typia.random<IAuthResponse>();
  export const simulate = (connection: IConnection, body: Body): Output => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: path(),
      contentType: "application/json",
    });
    assert.body(() => typia.assert(body));
    return random();
  };
}
