/**
 * @packageDocumentation
 * @module api.functional.payments.premium_status
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type { IConnection } from "@nestia/fetcher";
import { PlainFetcher } from "@nestia/fetcher";
import type { Resolved } from "typia";
import typia from "typia";

import type { IPremiumStatus } from "../../../structures/IPremiumStatus";

/**
 * 프리미엄 상태 확인.
 *
 * @tag Payment
 *
 * @controller PaymentController.premiumStatus
 * @path GET /payments/premium-status
 * @accessor api.functional.payments.premium_status.premiumStatus
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function premiumStatus(
  connection: IConnection,
): Promise<premiumStatus.Output> {
  return true === connection.simulate
    ? premiumStatus.simulate(connection)
    : PlainFetcher.fetch(connection, {
        ...premiumStatus.METADATA,
        template: premiumStatus.METADATA.path,
        path: premiumStatus.path(),
      });
}
export namespace premiumStatus {
  export type Output = IPremiumStatus;

  export const METADATA = {
    method: "GET",
    path: "/payments/premium-status",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = () => "/payments/premium-status";
  export const random = (): Resolved<IPremiumStatus> =>
    typia.random<IPremiumStatus>();
  export const simulate = (_connection: IConnection): Output => {
    return random();
  };
}
