/**
 * @packageDocumentation
 * @module api.functional.auth.nonce
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type { IConnection } from "@nestia/fetcher";
import { PlainFetcher } from "@nestia/fetcher";
import type { Resolved } from "typia";
import typia from "typia";

import type { INonceResponse } from "../../../structures/INonceResponse";

/**
 * SIWE 인증을 위한 일회용 nonce 발급.
 *
 * 프론트엔드가 MiniKit.walletAuth() 호출 전에 이 엔드포인트로 nonce를 받아간다.
 * nonce는 10분 TTL, 1회용 (사용 후 즉시 폐기).
 *
 * @tag Auth
 *
 * @controller AuthController.getNonce
 * @path GET /auth/nonce
 * @accessor api.functional.auth.nonce.getNonce
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function getNonce(
  connection: IConnection,
): Promise<getNonce.Output> {
  return true === connection.simulate
    ? getNonce.simulate(connection)
    : PlainFetcher.fetch(connection, {
        ...getNonce.METADATA,
        template: getNonce.METADATA.path,
        path: getNonce.path(),
      });
}
export namespace getNonce {
  export type Output = INonceResponse;

  export const METADATA = {
    method: "GET",
    path: "/auth/nonce",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = () => "/auth/nonce";
  export const random = (): Resolved<INonceResponse> =>
    typia.random<INonceResponse>();
  export const simulate = (_connection: IConnection): Output => {
    return random();
  };
}
