/**
 * @packageDocumentation
 * @module api.functional.payments.confirm
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type { IConnection } from "@nestia/fetcher";
import { NestiaSimulator, PlainFetcher } from "@nestia/fetcher";
import type { Resolved } from "typia";
import typia from "typia";

import type { IConfirmPaymentBody } from "../../../structures/IConfirmPaymentBody";
import type { IPaymentItem } from "../../../structures/IPaymentItem";

/**
 * 결제 검증 — MiniKit.pay() 응답 후 Developer Portal API로 검증.
 *
 * @tag Payment
 *
 * @controller PaymentController.confirmPayment
 * @path POST /payments/confirm
 * @accessor api.functional.payments.confirm.confirmPayment
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function confirmPayment(
  connection: IConnection,
  body: confirmPayment.Body,
): Promise<confirmPayment.Output> {
  return true === connection.simulate
    ? confirmPayment.simulate(connection, body)
    : PlainFetcher.fetch(
        {
          ...connection,
          headers: {
            ...connection.headers,
            "Content-Type": "application/json",
          },
        },
        {
          ...confirmPayment.METADATA,
          template: confirmPayment.METADATA.path,
          path: confirmPayment.path(),
        },
        body,
      );
}
export namespace confirmPayment {
  export type Body = IConfirmPaymentBody;
  export type Output = IPaymentItem;

  export const METADATA = {
    method: "POST",
    path: "/payments/confirm",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 201,
  } as const;

  export const path = () => "/payments/confirm";
  export const random = (): Resolved<IPaymentItem> =>
    typia.random<IPaymentItem>();
  export const simulate = (connection: IConnection, body: Body): Output => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: path(),
      contentType: "application/json",
    });
    assert.body(() => typia.assert(body));
    return random();
  };
}
