/**
 * @packageDocumentation
 * @module api.functional.auth
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type { IConnection } from "@nestia/fetcher";
import { PlainFetcher } from "@nestia/fetcher";
import type { Resolved } from "typia";
import typia from "typia";

import type { IAuthResponse } from "../../structures/IAuthResponse";

export * as nonce from "./nonce/index";
export * as wallet from "./wallet/index";
export * as dev_login from "./dev_login/index";

/**
 * JWT 기반 현재 유저 정보 조회.
 *
 * httpOnly 쿠키 또는 Authorization Bearer 헤더에서 JWT를 추출하여
 * 해당 유저의 정보를 반환한다.
 *
 * 응답 예시:
 * ```json
 * {
 *   "id": "550e8400-e29b-41d4-a716-446655440000",
 *   "world_id": "0xabcdef1234567890",
 *   "nickname": "User-a1b2c3d4",
 *   "created_at": "2026-04-24T00:00:00.000Z",
 *   "updated_at": "2026-04-24T00:00:00.000Z"
 * }
 * ```
 *
 * @returns 인증된 유저의 프로필 정보. 유저가 없으면 null.
 * @tag Auth
 *
 * @controller AuthController.me
 * @path GET /auth/me
 * @accessor api.functional.auth.me
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function me(connection: IConnection): Promise<me.Output> {
  return true === connection.simulate
    ? me.simulate(connection)
    : PlainFetcher.fetch(connection, {
        ...me.METADATA,
        template: me.METADATA.path,
        path: me.path(),
      });
}
export namespace me {
  export type Output = null | {
    created_at: string;
    updated_at: string;
    id: string;
    world_id: string;
    nickname: string;
    is_premium: boolean;
  };

  export const METADATA = {
    method: "GET",
    path: "/auth/me",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = () => "/auth/me";
  export const random = (): Resolved<null | {
    created_at: string;
    updated_at: string;
    id: string;
    world_id: string;
    nickname: string;
    is_premium: boolean;
  }> =>
    typia.random<null | {
      created_at: string;
      updated_at: string;
      id: string;
      world_id: string;
      nickname: string;
      is_premium: boolean;
    }>();
  export const simulate = (_connection: IConnection): Output => {
    return random();
  };
}

/**
 * 로그아웃 — 인증 쿠키를 삭제한다.
 *
 * 서버 측 세션은 없으므로 쿠키 삭제만으로 로그아웃이 완료된다.
 * JWT 자체는 만료 전까지 유효하지만, httpOnly 쿠키가 삭제되면
 * 브라우저가 더 이상 토큰을 전송하지 않는다.
 *
 * @tag Auth
 *
 * @controller AuthController.logout
 * @path POST /auth/logout
 * @accessor api.functional.auth.logout
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function logout(connection: IConnection): Promise<logout.Output> {
  return true === connection.simulate
    ? logout.simulate(connection)
    : PlainFetcher.fetch(connection, {
        ...logout.METADATA,
        template: logout.METADATA.path,
        path: logout.path(),
      });
}
export namespace logout {
  export type Output = IAuthResponse;

  export const METADATA = {
    method: "POST",
    path: "/auth/logout",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 201,
  } as const;

  export const path = () => "/auth/logout";
  export const random = (): Resolved<IAuthResponse> =>
    typia.random<IAuthResponse>();
  export const simulate = (_connection: IConnection): Output => {
    return random();
  };
}
