/**
 * @packageDocumentation
 * @module api.functional.roadmaps.match
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type { IConnection } from "@nestia/fetcher";
import { NestiaSimulator, PlainFetcher } from "@nestia/fetcher";
import type { Resolved } from "typia";
import typia from "typia";

import type { IMatchTemplateBody } from "../../../structures/IMatchTemplateBody";
import type { IMatchTemplateResult } from "../../../structures/IMatchTemplateResult";

/**
 * 임베딩 기반 유사 템플릿 로드맵 검색.
 *
 * @tag Roadmap
 *
 * @controller RoadmapController.matchTemplate
 * @path POST /roadmaps/match
 * @accessor api.functional.roadmaps.match.matchTemplate
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function matchTemplate(
  connection: IConnection,
  body: matchTemplate.Body,
): Promise<matchTemplate.Output> {
  return true === connection.simulate
    ? matchTemplate.simulate(connection, body)
    : PlainFetcher.fetch(
        {
          ...connection,
          headers: {
            ...connection.headers,
            "Content-Type": "application/json",
          },
        },
        {
          ...matchTemplate.METADATA,
          template: matchTemplate.METADATA.path,
          path: matchTemplate.path(),
        },
        body,
      );
}
export namespace matchTemplate {
  export type Body = IMatchTemplateBody;
  export type Output = IMatchTemplateResult;

  export const METADATA = {
    method: "POST",
    path: "/roadmaps/match",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 201,
  } as const;

  export const path = () => "/roadmaps/match";
  export const random = (): Resolved<IMatchTemplateResult> =>
    typia.random<IMatchTemplateResult>();
  export const simulate = (connection: IConnection, body: Body): Output => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: path(),
      contentType: "application/json",
    });
    assert.body(() => typia.assert(body));
    return random();
  };
}
